name: Push to GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prep and push mirror
        run: |
          USER=project_2367_bot
          git config user.password ${{ secrets.GITLAB_PUSH_KEY }}
          git config user.name ${USER}
          git remote add mirror 'https://${USER}@code.il2.dsop.io/chkodama/pdf-bullets.git'
          git push mirror
          
          
          
          
          
