name: Push to GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prep and push mirror
        run: |
          USER=project_2367_bot
          PASS=${{ secrets.GITLAB_PUSH_KEY }}
          echo 'echo $PASS' > ./creds.sh
          git config --global credential.helper cache
          git config --global credential.username ${USER}
          git config --global core.askPass ./creds.sh
          git remote add mirror 'https://code.il2.dsop.io/chkodama/pdf-bullets.git'
          git push mirror
          
          
          
          
          
